In [82]:
var_type_sparse = 1
var_type_dense = 0

class Variable(object):
    def __init__(self, key, var_size, var_type, delta_size=0):
        self.__var_size = var_size
        self.__var_type = var_type
        self.__var_key = key
        if delta_size == 0:
            self.__delta_size = var_size
        else:
            self.__delta_size = delta_size
        
    def var_size(self):
        return self.__var_size
    
    def var_type(self):
        return self.__var_type
    
    def var_key(self):
        return self.__var_key
    
    def var_delta(self):
        return self.__delta_size
    
    def __repr__(self):
        return 'var_key = {} var_size = {} delta_size = {} var_type = {}'.format(self.var_key(), self.var_size(), 
                                                                                 self.var_delta(),
                                                                                 self.var_type())

In [59]:
import numpy as np

class Jacobian(object):
    def __init__(self, w, h):
        self.__mat = np.zeros((w,h))
    
    def update(self, m):
        w, h = self.__mat.shape()
        assert(m.shape()[0] == w)
        assert(m.shape()[1] == h)
        self.__mat = m    
        
    def get(self):
        return self.__mat

In [97]:
class Factor(object):
    def __init__(self, keys, return_type):
        self.__set = True
        self.__keys = keys
        
    def keys(self):
        return self.__keys
    
    def error(variables):
        return 0
            
    def evaluate(variables, jacobians=None):
        assert(len(variables) == len(self.__keys))
        
        if not jacobians is None:
            assert(len(variables) == len(jacobians))
            for jac in jacobians:
                m = jac.get()
                jac.update(m)
        
        return error(variables)      

In [93]:
class Optimizer(object):
    def __init__(self):
        self.__variables_dense = list()
        self.__variables_sparse = list()
        self.__factors = list()
        
    def compose(self):
        M = 0
        for var in self.__variables_dense:
            M += var.var_delta()
        for var in self.__variables_sparse:
            M += var.var_delta()   
        H_full = np.zeros((M,M))
        return H_full
        
        
    def add_variable(self, variable):
        isinstance(variable, Variable)
        if variable.var_type == var_type_sparse:
            self.__variables_sparse.append(variable)
        else:
            self.__variables_dense.append(variable)
        
    def add_factor(self, factor):
        isinstance(factor, Factor)
        self.__factors.append(factor)
        
    def check(self):
        keys_needed = list()
        for factor in self.__factors:
            for key in factor.keys():
                if not key in keys_needed:
                    keys_needed.append(key)
        keys_missing = list()
        for var in self.__variables_dense:
            if var.var_key() in keys_needed:
                keys_needed.remove(var.var_key())
        for var in self.__variables_sparse:
            if var.var_key() in keys_needed:
                keys_needed.remove(var.var_key())
        if len(keys_needed) > 0:
            keys_missing = ''
            for key in keys_needed:
                keys_missing = '{} {}'.format(keys_missing, key)
            print("Keys missing {}".format(keys_missing))
            return False
        return True
            
    def solve(self):
        # Shur decompose
        return False
        

In [96]:
a = Variable('t', 3, var_type_dense)
print(a)

b = Variable('d', 1, var_type_sparse)
print(b)

c = Variable('c', 6, var_type_dense)
print(c)

opt = Optimizer()
opt.add_variable(a)
opt.add_variable(b)
opt.add_variable(c)

if opt.check():
    print("OK")
else:
    print("BAD")
    
print(opt.compose())

var_key = t var_size = 3 delta_size = 3 var_type = 0
var_key = d var_size = 1 delta_size = 1 var_type = 1
var_key = c var_size = 6 delta_size = 6 var_type = 0
OK
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [80]:
# Test system

0.4 * 0.4

0.16000000000000003

In [89]:
import numpy as np


J = np.zeros((3,5))
J[0,4] = 0.4
#J[:3,:3] = 0.5 * np.eye(3)
W = 3 * np.eye(3)
H = J.transpose().dot(W.dot(J))
print(H)
dx = np.zeros((5,1))
print(H.dot(dx))
r = np.zeros((3,1))

J.transpose().dot(r)

[[0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.48]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])